#!/bin/bash
#
# Notes:
# - The post-receive hook runs after the entire process is completed tp reload automatically the web app.
#   (cf https://help.pythonanywhere.com/pages/ReloadWebApp/)
#
# Installation:
# - On PythonAnywhere, in the cloned git repository folder, copy the current file into `.git/hooks/post-receive`.
# - Make sure the copied file is executable.
#
GIT_WORK_TREE='/home/tiger222/shaarlimages' git checkout -f
touch /var/www/www_shaarlimages_net_wsgi.py
