name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install -U pip 
          python -m pip install -r requirements-dev.txt
      - name: Run
        run: ./checks.sh

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install -U pip 
          python -m pip install -r requirements-dev.txt
      - name: Unit
        run: python -m pytest --doctest-modules host tests/unit
